overwrite: true
schema: https://countries.trevorblades.com/
schemaPath: schema.graphql
documents: ./src/*.graphql
generates:
    ./schema.graphql:
        - schema-ast
    src/generated.tsx:
        plugins:
        - 'typescript'
        - 'typescript-operations'
        - 'typescript-react-apollo'
        config:
            withHooks: true
